Fix Github action

diff --git a/.github/workflows/dotnet-core.yml b/.github/workflows/dotnet-core.yml
--- a/.github/workflows/dotnet-core.yml
+++ b/.github/workflows/dotnet-core.yml
@@ -23,12 +23,12 @@ jobs:
     - name: Test
       run: dotnet test --no-restore --logger "trx;LogFileName=tests.trx"
     - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: xUnit Tests
-          path: '**/*.trx'
-          reporter: dotnet-trx
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: xUnit Tests
+        path: '**/*.trx'
+        reporter: dotnet-trx
     - name: Pack library project
       run: dotnet pack src/Websocket.Client/Websocket.Client.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
     - name: Publish library (NuGet)
